### ISSUE TITLE
anisotropic_diffusion slicer error

### ISSUE THREAD

**Issue by nbianka99** [loli/medpy#115]
I get the error from below, even if I use the test function from your test file. My input is an image, which looks like the following:
`img = np.array(img, dtype=float)
filtered_img = anisotropic_diffusion(img)
`
The same error I get for:
`arr = np.random.uniform(size=(64,64))
filtered_img = anisotropic_diffusion(arr)
`
What am I doing wrong here? 
<img width="722" alt="error" src="https://github.com/loli/medpy/assets/42147654/017b7aa6-4ea3-4d51-80c1-79507fd5049d">

**Comment by 16jiu7** [comment]
https://github.com/loli/medpy/issues/90

**Comment by StellarStorm** [comment]
#107 looks to be the fix - will be merged in soon!

**Comment by loli** [comment]
Merged and fixed in Release 0.5.0
