### ISSUE TITLE
spelling: _extract_guassian_gradient_magnitude

### ISSUE THREAD

**Issue by samueljohn** [loli/medpy#14]
Wow, really nice collection of handy stuff in here.

I just noted in https://github.com/loli/medpy/blob/a3e62a26f1c62a521bdb0f559814ce0e8095b3f9/medpy/features/intensity.py#L341 there is reference a method name which is not defined. Looks like two chars are flipped (a,u). The doc string is also affected.

**Comment by loli** [comment]
Thanks for spotting that!

**Comment by loli** [comment]
Fixed.
