### ISSUE TITLE
Installation issues on Windows with Python 3.5.2

### ISSUE THREAD

**Issue by miroag** [loli/medpy#23]
Using Anaconda distro on Windows with Python 3.5.2 
I'm getting the error "ValueError: Unknown MS Compiler version 1900"
when pip install medpy or 
pip install git+https://github.com/loli/medpy
(Installation into venv with Python 2.7 went OK)
I need to convert an old and not mine project into P3.5, therefore sticking to 2.7 is not really an option
Complete error log is in the attached file
[import medpy error.txt](https://github.com/loli/medpy/files/763366/import.medpy.error.txt)

**Comment by loli** [comment]
Generally, **medpy** support neither Windows nor Python 3.

Although, in your case, the error seems to stem from the compilation of the _graphcut_ extension. You can try to install medpy without it. Simply download the source code and replace in _setup.py_ the 14 lines below

`### INSTALLATION`

with 

`run_setup(False)`

and run the setup with

> python setup.py install

which should trigger the medpy installation omitting the graphcut compilation step.

I hope that solves your problems.

**Comment by miroag** [comment]
OK, Thanks!

**Comment by loli** [comment]
Supporting the MS C++ compiler has to be considered an enhancement. Not likely to come soon.

**Comment by loli** [comment]
Won't fix
