### ISSUE TITLE
Comment in medpy.metric.binary.hd regarding connectivity is not correct

### ISSUE THREAD

**Issue by maxbernal** [loli/medpy#25]
"connectivity : int
The neighbourhood/connectivity considered when determining the surface of the binary objects. This value is passed to scipy.ndimage.morphology.generate_binary_structure and should usually be >1>1. **Presumably does not influence the result in the case of the Hausdorff distance.**"
I have tested in 3D objects and it actually has a big influence in the result.

**Comment by loli** [comment]
Thank you for the comment. I just took a short look at the code and the connectivity should not affect the HD distance, as far as I can tell. Will search for the problem before releasing the new version.

**Comment by maxbernal** [comment]
The calculation of the border depends on the connectivity.

# extract only 1-pixel border line of objects
result_border = result - binary_erosion(result, structure=footprint, iterations=1)
reference_border = reference - binary_erosion(reference, structure=footprint, iterations=1)

**Comment by loli** [comment]
Fixed with commit 7d52b40
