### ISSUE TITLE
'LazyITKModule' object has no attribute 'AnalyzeImageIO'

### ISSUE THREAD

**Issue by lxbcd94** [loli/medpy#26]
When I try to load an image, the error troubles me alot......
I run the following line:
from medpy.io import load
Iimage_data, image_header = load(test_data)
and the results are:
ImageLoadingError                         Traceback (most recent call last)
<ipython-input-7-4f8df22cca66> in <module>()
----> 1 image_data, image_header = load(test_data)

/home/lx/anaconda2/lib/python2.7/site-packages/medpy/io/load.pyc in load(image)
    199             logger.debug('Module {} signaled error: {}.'.format(loader, e))
    200 
--> 201     raise err
    202 
    203 def __load_nibabel(image):

ImageLoadingError: Failes to load image /home/lx/Personal/source code/lasc-master/data/mri/testing/b002/image.mhd as Itk/Vtk MetaImage (.mhd, .mha/.raw). Reason signaled by third-party module: 'LazyITKModule' object has no attribute 'AnalyzeImageIO'

**Comment by loli** [comment]
See Issue #15.
