### ISSUE TITLE
Python 3 compatibility for anisotropic_diffusion

### ISSUE THREAD

**Issue by Overdrivr** [loli/medpy#29]
I've installed medpy from master branch, however I'm still getting a Python 3 incompatibility, `xrange` function was removed in py3 and replaced by `range`. For short lists, it should not make a difference in Python 2. 

```
   [...]\src\medpy\medpy\filter\smoothing.py", line 135, in anisotropic_diffusion
    deltas = [numpy.zeros_like(out) for _ in xrange(out.ndim)]
NameError: name 'xrange' is not defined
```
I can make the changes and a PR if you're interested, let me know

**Comment by loli** [comment]
Thank you very much, that would be most welcoem. I hope to get MedPy P3-ready for the next release, but I am always missing something.

**Comment by Overdrivr** [comment]
Sure, no problem. I'll try to get it done today or tommorow

**Comment by Overdrivr** [comment]
See #31
