### ISSUE TITLE
pytest to unittest conversion

### ISSUE THREAD

**Issue by loli** [loli/medpy#33]
To ensure compatibility over all tests. Affects file 
https://github.com/loli/medpy/blob/master/tests/metric_/histogram.py
only.

**Comment by raamana** [comment]
Thanks Oscar, I will try to convert them to unittest when I get a chance.

Also, I've improved these tests significantly within my own package, using hypothesis testing framework.. Take a look if you get a chance:
https://github.com/raamana/hiwenet/blob/master/hiwenet/test_medpy.py

**Comment by Overdrivr** [comment]
Why not move all tests to the more concise pytest syntax ? I believe it is also compatible with other test runners like `nose`

**Comment by loli** [comment]
That would be a good idea for the release after the next. But for now all should be as usable as possible with minimum effort.

@raamana 
Running `pytest metric_/histogram.py`, two of the four test fails. Could you fix this, please?

**Comment by loli** [comment]
Just tried nosetests on it... it does not seem to work.

**Comment by raamana** [comment]
Check #40 - it will very likely fix it.

**Comment by loli** [comment]
Thanks you! Solved with merge 36a5919
