### ISSUE TITLE
Need DOI to cite this package

### ISSUE THREAD

**Issue by raamana** [loli/medpy#34]
Hi, I think you should get a DOI for this package, so others like me can cite this package properly. Let me know once you get it from places like Zenodo.

**Comment by loli** [comment]
Added with commit ccc3d78

@raamana : Here you are: [![DOI](https://zenodo.org/badge/4295983.svg)](https://zenodo.org/badge/latestdoi/4295983)

**Comment by raamana** [comment]
Are you sure you want your name to be `loli`? Or was it an oversight? :)

**Comment by loli** [comment]
Oversight, thanks! Neat tool, this Zenodo thing :)
