### ISSUE TITLE
Need new PyPI release

### ISSUE THREAD

**Issue by raamana** [loli/medpy#35]
The current release on pypi doesn't work for python 3, due to single error in syntax (merged pull request) raising a runtime error. Since its been 3 years, its time to release another version with all the bug fixes so far. Thanks.

**Comment by loli** [comment]
You are definitely rights, its high time for a new release. The main problem is that a buggy release is worse than none at all... and there are still some problems that persist.

I will try to find the time to run a couple of python 2 and python 3 virgin installs of medpy from the current master to identify the remaining problems and then release a new version.

Did you get medpy to run under python 3 reliably?

**Comment by raamana** [comment]
When I manually fix the syntax error (adding parentheses to the runtime
exception message to raise), it runs. Given that I verified some of the
histogram metrics are indeed metrics, I think I will be happy if you can
make a release - perhaps you can call this version beta if you wanted to
warn people. I'd appreciate that.

**Comment by loli** [comment]
Here you are, @raamana : https://pypi.python.org/pypi/MedPy

**Comment by raamana** [comment]
Thanks Oskar, now my packages test successfully on CI on Py 3+ also 👍
