### ISSUE TITLE
Automatic Conductance Parameter (kappa) for Anisotropic Diffusion Filtering

### ISSUE THREAD

**Issue by cancan101** [loli/medpy#54]
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.449.948&rep=rep1&type=pdf offers four different ways of setting the kappa automatically.

**Comment by loli** [comment]
Any experience with how well these work?

**Comment by cancan101** [comment]
Not really. The first option (canny) was reference in the original P & M paper. The other have been introduced in various other papers over time. It might be cool to have Python implementations of these for people to experiment, etc

**Comment by loli** [comment]
Would your proposed change of #62 solve this question? Or would you additionally like to implement these functions, too?

**Comment by loli** [comment]
Closed due to inactivity.
