### ISSUE TITLE
Cut a release 

### ISSUE THREAD

**Issue by cancan101** [loli/medpy#67]
Now that https://github.com/loli/medpy/pull/60 is merged, can we get a new release of medpy to pypi?

**Comment by cancan101** [comment]
Someone else interested too: https://github.com/ofgulban/segmentator/issues/62#issuecomment-366215905

**Comment by loli** [comment]
Sure thing. I've started a project for the release of 0.4.0 with a to do list. You think the items on that list reasonable? Anything you feel is missing or too much?

**Comment by cancan101** [comment]
I dont think #61 and #54 need to be in this release

**Comment by loli** [comment]
Agreed.

**Comment by loli** [comment]
Started working on it in branch https://github.com/loli/medpy/tree/Release_0.4.0

**Comment by cancan101** [comment]
Ping on getting a release cut?

**Comment by loli** [comment]
Sure. I'll try to get some of the WPs done next week. Would you be able to help with some?

https://github.com/loli/medpy/projects/3

**Comment by cancan101** [comment]
sure, what todos do you have in mind? Most of the project items look like part of the release process itself.

**Comment by loli** [comment]
I would call them more testing items... sadly not very interesting work. But releasing a version that does not work in the end is very damaging for the reputation and creates more work than the testing (I've been there).

You could build a release, upload it to the PyPi test server and than install it under different Python versions and environments (virtual machines) using the installation instructions (https://loli.github.io/medpy/). Any deviations or error you note: Just write them down so we can fix them.

Thanks!

**Comment by loli** [comment]
Done with release 0.4.0 with P3 support.
