### ISSUE TITLE
TypeError with medpy.metric.binary

### ISSUE THREAD

**Issue by anjany** [loli/medpy#72]
When using 'medpy.metric.binary.hd' or 'medpy.metric.binary.asd', I get the following error: 

> TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

With stack trace pointing to a line in medpy/metric/binary.pyc
`1169     result_border = result - binary_erosion(result, structure=footprint, iterations=1)`

Does the operator need any update? (I'm using MedPy 0.3.0)

**Comment by wasserth** [comment]
I am having the same problem if I install from pip. If I build directly from master it works fine.

**Comment by loli** [comment]
Thanks for the solution @wasserth 
Please use the current master, we are planning on pushing a new release, soon.
