### ISSUE TITLE
one error in binary.py

### ISSUE THREAD

**Issue by qianshuqinghan** [loli/medpy#75]
def true_negative_rate(result, reference):
    """
    True negative rate.
    Same as :func:`sensitivity`, see there for a detailed description.
    
    See also
    --------
    :func:`true_positive_rate` 
    :func:`positive_predictive_value`
    """
    return sensitivity(result, reference)

the true negative rate equals to specificity, instead of sensitivity

**Comment by loli** [comment]
Fixed with 4e2e2e9 

Thank you!
