### ISSUE TITLE
Import Error: no module named 'filter'

### ISSUE THREAD

**Issue by yxie060** [loli/medpy#82]
Hi,

I am trying to read some images (in either mha or nrrd format) with medpy (release 0.3.0) on windows 7. I do have installed pydicom, nibabel, and itk. There were no warning or error messages during the installation via pip. However, when I tried to read the images, it failed with the following:

DependencyError:  Loading images of type Nrrd - Nearly Raw Raster Data (.nhdr, .nrrd) requires a third-party module that could not be encountered. Reason: No module named 'filter'.

The same situation with mha files. 

Any help is appreciated!

**Comment by loli** [comment]
Unfortunately, I cannot provide support for issues occurring on Windows. Best use MedPy on a linux machine.

**Comment by loli** [comment]
It might also be worth trying the current master branch from github.
