### ISSUE TITLE
ModuleNotFoundError: No module named 'medpy.graphcut.maxflow'

### ISSUE THREAD

**Issue by varanasivenkatsai** [loli/medpy#87]
Hi,

I am trying to use graphcut from medpy, but unfortunately i found it works only on python 2.7. So i created virtual environment in conda and installed medpy 0.3.0 on python 2.7. But the error remains same.
This is the error message:

from .maxflow import GraphDouble, GraphFloat, GraphInt # this always triggers an error in Eclipse, but is right

ImportError: No module named maxflow

**Comment by varanasivenkatsai** [comment]
Update:
when i tried to install by cloning from github i am getting this error.

WARNING: The medpy.graphcut.maxflow external C++ package could not be compiled, all graphcut functionality will be disabled. You might be missing Boost.Python or some build essentials like g++.
Plain-Python installation succeeded.

**Comment by loli** [comment]
Did you install the requirements for the graphcut package as detailed in the documentation http://loli.github.io/medpy/installation/graphcutsupport.html?

And which OS are you working on? It most likely won't work under windows.

**Comment by varanasivenkatsai** [comment]
I am using windows OS. I installed gcc and libboost from anaconda but still its showing same error.Is there any other way to run this for windows? What would be easy way to install other platforms in my computer? and  which platform the maxflow is ideally designed for?

**Comment by loli** [comment]
Medpy has no official support for windows. Although all but the graph cut package seem to work.

I never got the graph cut package to compile with the conda libboost. You can try to do it by hand... But it might be quite some work. And I would be interested on how you managed to add the support :)

On Ubuntu everything should work fine of you follow the installation instruction for an installation with graph cut support.

**Comment by varanasivenkatsai** [comment]
Hi again,
As you have mentioned I have installed ubuntu and ran a sample program on gaphcut and its running very perfectly. but when i run on my image. It gives this error

b = np.broadcast(*args[:32])

ValueError: shape mismatch: objects cannot be broadcast to a single shape



Testing is done for an image size 5x5. My original image is of size 3200x3200. This function is not meant for these sizes? what to change in source to adjust to it.

Thanks

**Comment by varanasivenkatsai** [comment]
Hi again,
As you have mentioned I have installed ubuntu and ran an example on graphcut and it works fine. But after getting the graph. to get its weights its giving me error:

'GraphDouble' object has no attribute 'get_nweight'.

And when in run graph_from_labels functions with boundaryterm=boundary_difference _ofmeans  like this:
graph = graph_from_labels(label_image,fg_marker,bg_marker, boundary_term=medpy.graphcut.energy_label.boundary_difference_of_means(graph, label_image, dst1[:,:,2]))

This is the error i got:

graph.set_nweight(edge[0] - 1, edge[1] - 1, value, value)

AttributeError: 'Graph' object has no attribute 'set_nweight'
