### ISSUE TITLE
metrics for multi-classes?

### ISSUE THREAD

**Issue by hubutui** [loli/medpy#94]
Currently, all metric measures in https://loli.github.io/medpy/metric.html are for binary only. Any plan to add support for multiple classes?

**Comment by loli** [comment]
I currently do not plan that. But any contributions are very welcome.

Metrics for multiple classes are notoriously fickle and have to be defined with the application in mind. More often than not, no generally agreed on definition exists (e.g., is label A when falsely classified B still 'more' correct than if it would have been falsely classified as C?).
